"""
Title:          PyCloudSim
Description:    A Python-based Cloud Simulator
Author(s):      Mahmoud Momtazpour
Licence:        GPL - https://www.gnu.org/copyleft/gpl.html
Copyright (c) 2022-2023, Amirkabir University of Technology, Iran
"""


class VM:
    """ A VM (Virtual Machine) is an entity that runs inside a host, and consumes its resources
    (mips, ram, bw and storage)
    :ivar _vm_id: id of VM
    :type _vm_id: int
    :ivar _user_id: id of the user that submitted this VM
    :type _user_id: int
    :ivar _vm_uid: a unique id of VM that is generated by concatenating vm_id and user_id
    :type _vm_uid: str
    :ivar _mips: VM requested mips
    :type _mips: int
    :ivar _ram: VM requested ram
    :type _ram: int
    :ivar _storage: VM requested storage
    :type _storage: int
    :ivar _bw: VM requested bandwidth
    :type _bw: int
    :ivar _current_allocated_mips: VM allocated mips
    :type _current_allocated_mips: int
    :ivar _current_allocated_ram: VM allocated ram
    :type _current_allocated_ram: int
    :ivar _current_allocated_storage: VM allocated storage
    :type _current_allocated_storage: int
    :ivar _current_allocated_bw: VM allocated bandwidth
    :type _current_allocated_bw: int
    :ivar _vmm: VM Virtual Manager
    :type _vmm: str
    :ivar _arrival_time: arrival time of VM
    :type _arrival_time: int
    :ivar _duration: duration of VM
    :type _duration: int
    :ivar _host: the host that the VM allocated to
    :type _host: Host
    """
    def __init__(self, vm_id, user_id, mips, ram, bw, storage, vmm, arrival_time, duration):
        self._vm_id = vm_id
        self._user_id = user_id
        self._vm_uid = str(user_id) + '-' + str(vm_id)
        self._mips = mips
        self._ram = ram
        self._bw = bw
        self._storage = storage
        self._vmm = vmm
        self._arrival_time = arrival_time
        self._duration = duration
        self._current_allocated_bw = 0
        self._current_allocated_mips = 0
        self._current_allocated_ram = 0
        self._current_allocated_storage = 0
        self._host = None

    def get_id(self):
        return self._vm_id

    def set_id(self, vm_id):
        self._vm_id = vm_id

    def get_vm_uid(self):
        return self._vm_uid

    def set_vm_uid(self, uid):
        self._vm_uid = uid

    def get_user_id(self):
        return self._user_id

    def set_user_id(self, user_id):
        self._user_id = user_id

    def get_mips(self):
        return self._mips

    def set_mips(self, mips):
        self._mips = mips

    def get_ram(self):
        return self._ram

    def set_ram(self, ram):
        self._ram = ram

    def get_bw(self):
        return self._bw

    def set_bw(self, bw):
        self._bw = bw

    def get_storage(self):
        return self._storage

    def set_storage(self, storage):
        self._storage = storage

    def get_vmm(self):
        return self._vmm

    def set_vmm(self, vmm):
        self._vmm = vmm

    def get_current_allocated_bw(self):
        return self._current_allocated_bw

    def set_current_allocated_bw(self, current_allocated_bw):
        self._current_allocated_bw = current_allocated_bw

    def get_current_allocated_mips(self):
        return self._current_allocated_mips

    def set_current_allocated_mips(self, current_allocated_mips):
        self._current_allocated_mips = current_allocated_mips

    def get_current_allocated_ram(self):
        return self._current_allocated_ram

    def set_current_allocated_ram(self, current_allocated_ram):
        self._current_allocated_ram = current_allocated_ram

    def get_current_allocated_storage(self):
        return self._current_allocated_storage

    def set_current_allocated_storage(self, current_allocated_storage):
        self._current_allocated_storage = current_allocated_storage

    def get_host(self):
        return self._host

    def set_host(self, host):
        self._host = host

    def get_arrival_time(self):
        return self._arrival_time

    def get_duration(self):
        return self._duration

